/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
/Users/gmorra/Desktop/minishell$
